xproject/urls.py
from django.contrib import admin
from django.urls import path
from books.views import BooksPage, BookDetailview , create_book_form_view, book_form_view, contact_form_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/',BooksPage.as_view(), name = 'books_list'),
    path("books/<int:pk>/", BookDetailview.as_view(), name="book_detail"),
    path('create-book/', create_book_form_view, name='create_book_form_view'),
    path('add-book/', book_form_view, name='book_form'),
    path('contact/', contact_form_view, name='contact_form'),
]

books/models/book.py
from django.db import models
from django.urls import reverse


class Publisher(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"publisher's name :   {self.name}"
    


class Author(models.Model):
    name = models.CharField(max_length= 30)

    def __str__(self):
        return self.name
    


class Book(models.Model):
    name = models.CharField(max_length=50)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    review = models.TextField(max_length=1500, blank=True, null=True)


    def __str__(self):
        return f"Books store: {self.name}"

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

books/models/contact.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField(max_length=2500, blank=True, null=True)

    def __str__(self):
        return f'Contact : {self.name}'

books/forms/form.py
from django import forms
from ..models.book import Author
from ..models.book import Publisher
from ..models.book import Book
from ..models.contact import Contact

class CreateBookForm(forms.Form):
      name = forms.CharField(max_length=20)

      publisher = forms.ModelChoiceField(
         queryset= Publisher.objects.all(),
         label='Publisher',
         required=False
      )

      author = forms.ModelChoiceField(
         queryset= Author.objects.all(),
         label= 'Author',
         required=False
      )

      review = forms.CharField(widget=forms.Textarea, required=False) 


class BookForm(forms.ModelForm):
      class Meta:
            model = Book
            fields = ['name','author', 'publisher', 'review']

            

class ContactForm(forms.ModelForm):
     class Meta:
           model = Contact
           fields = ['name', 'content']
           widgets = {'name': forms.TextInput(attrs = {'class': 'form-control'})}
      

books/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.generic import ListView,  DetailView
from .models.book import Book
from .forms.form import CreateBookForm ,  BookForm,  ContactForm


class BooksPage(ListView):
    template_name =  'books.html'
    model = Book
    context_object_name = 'books_list'


class BookDetailview(DetailView):
    template_name = 'book_details.html'
    model = Book
    context_object_name = 'book'


def create_book_form_view(request):
     if request.method == 'POST':
        form = CreateBookForm(request.POST)
        if form.is_valid():
            model = Book(
                name = form.cleaned_data['name'],
                author = form.cleaned_data['author'],     
                publisher = form.cleaned_data['publisher'],
                review = form.cleaned_data['review']
            )
            model.save()
            return render(request, 'form_success.html', {'name': model.name})
     else:
        form = CreateBookForm()

     return render(request, 'form_template.html', {'form':form})        



def book_form_view(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = BookForm()  
    return render(request, 'book_form.html', {'form': form})

def contact_form_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
         form = ContactForm()

    users = {'name':'moj',
             'lastName' : 'hhh',
             'age': 20
             }     
    return render(request, 'contact_form.html', {'myForm': form, 'user' : users})    

        

books/templates/book_details.html
{% extends 'master.html' %} {% block content %}
<div class="d-flex justify-content-center align-items-center bg-light">
  <div class="container my-5">
    <div class="card shadow-sm">
      <div class="card-body">
        <h2 class="card-title text-primary mb-3">{{ book.name }}</h2>
        <hr />
        <p><strong>Author:</strong> {{ book.author }}</p>
        <p><strong>Publisher:</strong> {{ book.publisher }}</p>
        <p><strong>Review:</strong> {{ book.review }}</p>
        <a href="{% url 'books_list' %}" class="btn btn-secondary mt-3"
          >Back to Books List</a
        >
      </div>
    </div>
  </div>
</div>

{%endblock content%}

books/templates/book_form.html
<h1>Add a Book</h1>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

books/templates/books.html
{% extends 'master.html' %} {% block content %}

<div class="container my-5">
  <h2 class="text-center mb-4">Books List</h2>
  <div class="row g-4">
    {% for book in books_list %}
    <div class="col-md-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title text-primary">
            <a href="{{book.get_absolute_url}}">{{ book.name }}</a>
          </h5>
          <hr />
          <p class="card-text text-muted">Author: {{ book.author }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{%endblock content%}

books/templates/contact_form.html
{% extends "master.html" %}{% block content%}
<h1>Contact Us</h1>
<form class="container" method="post">
  {% csrf_token %}

  <div class="p-3">{{myForm.name.label_tag}} {{myForm.name}}</div>
  <button type="submit">Send</button>
</form>
<h1>{{user.name}}</h1>
{% endblock %}

books/templates/form_success.html
{% extends 'master.html' %} {% block content %}
<div class="container">
  <h1 class="alert alert-success text-center" role="alert">Success</h1>
</div>
{%endblock content%}

books/templates/form_template.html
{% extends 'master.html' %} {% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6 bg-light p-4 rounded shadow">
      <h2 class="text-center mb-4">Create Book Form</h2>
      <form method="post" action="{% url 'create_book_form_view' %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="id_name" class="form-label">Name</label>
          {{ form.name }}
        </div>
        <div class="mb-3">
          <label for="id_publisher" class="form-label">Publisher</label>
          {{ form.publisher }}
        </div>
        <div class="mb-3">
          <label for="id_author" class="form-label">Author</label>
          {{ form.author }}
        </div>
        <div class="mb-3">
          <label for="id_review" class="form-label">Review</label>
          {{ form.review }}
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

books/templates/master.html
<head>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
    crossorigin="anonymous"
  />
  <style>
    .body {
      background-color: #274060;
      color: #e6e6e6;
      font-family: "Arial", sans-serif;
      margin: 1rem;
      padding: 1rem;
    }
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 2.5rem;
      color: #d3d3d3;
    }
    .header p {
      font-size: 1.2rem;
      color: #cfcfcf;
      margin-button: 1rem;
    }
    .lists {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 20px;
      margin: 2rem auto;
    }
    .list {
      background-color: #1c2b40;
      padding: 15px 20px;
      text-align: center;
      width: 150px;
      color: #e6e6e6;
      position: relative;
    }
    .list span {
      font-size: 1rem;
      font-weight: bold;
    }
    .list p {
      font-size: 0.9rem;
    }
    .checked {
      position: absolute;
      right: -12;
      top: 0;
      height: 100%;
      width: 5px;
      background-color: #4caf50;
      border-radius: 2px;
    }
    main {
      margin: 2rem auto;
      padding: 1rem;
      max-width: 900px;
    }

    footer {
      background-color: #1c2b40;
      padding: 1rem;
      text-align: center;
      color: #cfcfcf;
      margin-top: 2rem;
    }

    footer a {
      color: #4caf50;
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="body">
    <div class="header">
      <h1>Books For Reading</h1>
      <p>This is a list of books that you can read.</p>
    </div>
    <main class="lists">
      <div class="list">
        <a class="nav-link d-inline text-white" href="{% url 'books_list'%}">
          <span>Books</span>
          <p>Start Doodling</p>
          <div class="checked"></div>
        </a>
      </div>
      <div class="list">
        <span>item one</span>
        <p>Start Doodling</p>
        <div class="checked"></div>
      </div>
      <div class="list">
        <span>item two</span>
        <p>Start Doodling</p>
      </div>
    </main>
    <footer>
      <a href="{% url 'book_form' %}">Add a Book</a>
      <a href="{% url 'contact_form'%}">Contact</a>
    </footer>
  </div>
</body>

{% block content %} {% endblock content %}